### ISSUE TITLE
Report on current trickling filter issues and proposed solutions 

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#6]
For our first iteration of the research report, we would like to have a report on what issues we have identified in current trickling filter and our proposed solutions to these issues.

**Comment by jillianwhiting** [comment]
Report created as BOD_Model in repo

**Comment by BenGassaway** [comment]
Portal Time: 5f10c9e4-384c-43cb-8032-a85e02babdb1

**Comment by rosiekrasnoff** [comment]
portal: 574d18ab-9198-4b0c-9a27-8f50594e0607

**Comment by rosiekrasnoff** [comment]
I added pictures from the tour in Case Study section, please advise on how to properly label/ integrate. Should I put them in the middle of the text where they are mentioned or at the end? If they go in where they are mentioned, labeling seems redundant.

Also, they are very large. Not sure I have the skills to make them smaller...

**Comment by jillianwhiting** [comment]
Portal Time: 9fa4abe4-eb92-4c41-86da-8bb4c6b66dd1

**Comment by rosiekrasnoff** [comment]
portal time bois:
de999fb7-aa05-41db-8b06-8f02a7532467

**Comment by rosiekrasnoff** [comment]
@jillianwhiting I moved your section on nitrogen to underneath the BOD kinetics, I felt like it should be under the literature review section but feel free to move it back if you disagree

**Comment by BenGassaway** [comment]
It's portal time dudes: 8e43bfa5-4616-4806-aca3-52b8bbefc22e

**Comment by BenGassaway** [comment]
@rosiekrasnoff @jillianwhiting do I need to have the blue-text link for my citation if I'm using the metcalf book, or are you guys just doing that for pdf references?

**Comment by rosiekrasnoff** [comment]
@BenGassaway I don't think you need a link, there's nothing to link it to anyway

**Comment by jillianwhiting** [comment]
@BenGassaway  I agree with rosie the bibliography is done, do you want to be in charge of sending it in at the end of the night

**Comment by BenGassaway** [comment]
@jillianwhiting @rosiekrasnoff I am happy to submit for us! Aside from pushing the final report to our repository, who do I need to email the report to for an official submission?

**Comment by jillianwhiting** [comment]
@BenGassaway 
send a link to aguaclaragraders@gmail.com

**Comment by BenGassaway** [comment]
@jillianwhiting @rosiekrasnoff finishing up my sections and submitting soon--since we haven't constructed anything, I may hold off on the experimental apparatus. I included a procedure for our first benchtop experiment. Thoughts? I will review and submit if you guys are comfortable with what we have for the moment

**Comment by rosiekrasnoff** [comment]
@BenGassaway I think that's fine, we since we haven't actually constructed anything yet, any of the sections that you don't feel like you can answer can just be skipped. I gave the conclusion a shot, if you could add a couple sentences about your research that would be good (I figured its easier for you to write it yourself in a few minutes than me trying to read/understand your sections and then summarize them). Then I think it's ready to send in!

**Comment by BenGassaway** [comment]
@rosiekrasnoff Got it, thanks so much! Everything looks good to me. I'll add my concluding sentences. Great work guys!
