### ISSUE TITLE
Build prototypes for proposed solution

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#7]

**Comment by rosiekrasnoff** [comment]
Currently working on construction of preliminary model for a new concept of a trickling filter. Model is an overflowing basin with strings coming out and down the sides. Idea is the biofilm would grow on the strings and treat BOD/nutrients as water flows down the strings. 

A problem we have encountered is that we need to ground the strings and keep them taut in order to keep the strings orderly and keep flow somewhat organized, but with the number of strings that are being used, we need to find a way to ground them that is easy and quick so as to not be too time intensive.

**Comment by jillianwhiting** [comment]
![img_4135](https://user-images.githubusercontent.com/31287881/39599729-9b201520-4eea-11e8-87cf-91ee8f12ed46.JPG)
Here is a photo of the prototype the team made. It is a basin that fills with water and overflows onto the strings,  the water flows (trickles) down the strings
